// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AnimeListApi.Models.Data;

public partial class Anime
{
    public int Animeid { get; set; }

    public string Title { get; set; }

    public string Image { get; set; }

    public string Type { get; set; }

    public int? Episodecount { get; set; }

    public string Season { get; set; }

    public int? Releaseyear { get; set; }

    public virtual ICollection<Animelist> Animelist { get; set; } = new List<Animelist>();
}