// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AnimeListApi.Models.Data;

public partial class Characters
{
    public int Characterid { get; set; }

    public string Name { get; set; }

    public string Image { get; set; }

    public virtual ICollection<Favoritecharacters> Favoritecharacters { get; set; } = new List<Favoritecharacters>();
}