// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AnimeListApi.Models.Data;

public partial class Manga
{
    public int Mangaid { get; set; }

    public string Title { get; set; }

    public string Image { get; set; }

    public int? Chaptercount { get; set; }

    public int? Releaseyear { get; set; }

    public virtual ICollection<Mangalist> Mangalist { get; set; } = new List<Mangalist>();
}