// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AnimeListApi.Models.Data;

public partial class Profiles
{
    public Guid Id { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Username { get; set; }

    public string AvatarUrl { get; set; }

    public string Bio { get; set; }

    public virtual ICollection<Animelist> Animelist { get; set; } = new List<Animelist>();

    public virtual ICollection<Favoritecharacters> Favoritecharacters { get; set; } = new List<Favoritecharacters>();

    public virtual ICollection<Mangalist> Mangalist { get; set; } = new List<Mangalist>();
}