// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AnimeListApi.Models.Data;

public partial class Status
{
    public int Statusid { get; set; }

    public string Statusname { get; set; }

    public virtual ICollection<Animelist> Animelist { get; set; } = new List<Animelist>();

    public virtual ICollection<Mangalist> Mangalist { get; set; } = new List<Mangalist>();
}